# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "checkout-upsell"
handle = "checkout-upsell"
type = "ui_extension"
uid = "42a78221-416b-44aa-07ba-7ad811835d0691422ded"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.cart-line-list.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition

[extensions.settings]

[[extensions.settings.fields]]
key = "products_view"
type = "boolean"
name = "Show carousel view"
description = "Configure products view carousel or stack"

[[extensions.settings.fields]]
key = "product_count"
type = "number_integer"
name = "Max product count"
description = "Maximum number of products to be added at a time"

[[extensions.settings.fields]]
key = "product_variant_1"
type = "variant_reference"
name = "1st variant"
description = "Choose 1st variant"

[[extensions.settings.fields]]
key = "product_variant_2"
type = "variant_reference"
name = "2nd variant"
description = "Choose 2nd variant"

[[extensions.settings.fields]]
key = "product_variant_3"
type = "variant_reference"
name = "3rd variant"
description = "Choose 3rd variant"


